import { fallback } from "./fallback";
import { ITranslation } from "./translation";

const translated: Partial<ITranslation> = {
	'账号信息': 'Account Information',
  '账号设置': 'Account Settings',
  '退出登录': 'Logout',
  '搜索': 'Search',
  '首页': 'Home',
  '客户关系': 'Customer Relationship',
  '委托单位': 'Trustor',
  '元数据': 'Metadata',
  '设备管理': 'Device Management',
  '设备数据': 'Device Information',
  '报告管理': 'Report Management',
  '设备检验检测': 'Device Inspection',
  '仪表盘': 'Dashboard',
  '设备': 'Device',
  '创建后继续': 'Create and Continue',
  '成功': 'Success',
  '失败': 'Failed',
  '新增': 'Add',
  '保存': 'Save',
  '列表': 'List',
  '每页显示': 'Page Size',
  '非开发人员不要修改': 'DO NOT MODIFY IF YOU ARE NOT A DEVELOPER',
  '关闭': 'Close',
  '确认': 'Confirm',
  '此操作不可逆，可能会影响设备列表数据，请谨慎!': 'CAUTION: This operation is irreversible and may affect the device list data. Please be careful!',
  '操作': 'Operation',
  '批量删除': 'Batch Delete',
  '编辑': 'Edit',
  '详情': 'Details',
  '设备类型': 'Device Type',
  '检测项标识': 'Detection Item',
  '检测项名称': 'Detection Name',
  '检测类型': 'Detection Type',
  '计算公式': 'Formula',
  '备注': 'Remark',
  '选择设备': 'Select Device',
  '登录': 'Login',
  '账号': 'Username',
  '密码': 'Password',
	'没有账号？': 'No Account?',
  '注册一个': 'Register',
  '欢迎回村，请登录': 'Welcome back, please login',
  '欢迎您，': 'Welcome,',
  '进入系统': 'Enter',
  '请填写登录名': 'Please enter username',
  '请输入密码': 'Please enter password',
  '加载中': 'Loading',
  '确定': 'Confirm',
  '取消': 'Cancel',
  '客户': 'Customer',
  '请选择客户': 'Please select customer',
  '搜索以选择客户': 'Search to select customer',
  '搜索结果为空': 'Search result is empty',
  '输入客户名称进行精确搜索': 'Enter customer name for accurate search',
  '地址': 'Address',
  '详细地址': 'Detailed Address',
	'过滤': 'Filter',
  '过滤数据项': 'Filter',
  '全选': 'Select All',
  '暂无数据': 'No Data',
  '删除节点': 'Delete Node',
  '增加兄弟节点': 'Add Sibling Node',
  '数据类型': 'Data Type',
  '新增键值对': 'Add Key-Value Pair',
	'下一步': 'Next',
	'登录名不能有空格': 'Username cannot contain spaces',
	'设备详情': 'Device Details',
	'请选择设备类型': 'Please select device type',
	'无': 'None',
	'检测依据': 'Detection Basis',
	'样品标识': 'Sample Identifier',
	'制造厂商': 'Manufacturer',
	'设备型号': 'Device Model',
	'设备场所': 'Device Location',
	'检测仪器': 'Detection Instrument',
	'检测项目': 'Detection Item',
	'创建时间': 'Created At',
	'更新时间': 'Updated At',
	'创建人': 'Created By',
	'类型标识': 'Type Identifier',
	'设备名称': 'Device Name',
	'设备编号': 'Device Number',
	'检测日期': 'Detection Date',
	'生成报告': 'Report Generation',
	'检测结果': 'Result',
	'检测条件': 'Condition',
	'检测指标要求': 'Requirements',
	'结论': 'Conclusion',
	'验收检测': 'Acceptance Inspection',
	'状态检测': 'Status Inspection',
	'删除': 'Delete',
	'设备类型标识': 'Device Type Identifier',
	'可用检测项目': 'Available Detection Items',
	'上传附件': 'Upload Attachment',
	'查看': 'View',
	'基本信息': 'Basic Information',
	'使用建议': 'Apply Advice',
	'合格': 'Qualified',
	'不合格': 'Unqualified',
	'未知': 'Unknown',
	'辐射': 'Radiation',
	'值': 'Value',
	'电压': 'Voltage',
	'电流': 'Current',
	'时间': 'Duration',
	'专用检测项目':	'Special Detection Items',
	'通用检测项目':	'General Detection Items',
	'报告编号': 'Report Number',
	'时间积': 'Time Integral',
	'管电流': 'Tube Current',
	'预设值': 'Preset Value',
	'县级': 'County',
	'地级': 'Prefecture',
	'测量值': 'Measured Value',
	'结果': 'Result',
	'基线': 'Baseline',
	'平均像素值': 'Average Pixel Value',
	'行': 'rows',
	'总量': 'Total',
	'当前范围': 'Current Range',
}

export const resources: ITranslation = fallback<ITranslation>(translated)