Skip to content
Search or jump to…
Pull requests
Issues
Marketplace
Explore

@shijinyu
mingyang91
/
doc-man-ui
Private
Code
Issues
Pull requests
Actions
Projects
Security
Insights
doc-man-ui/.github/workflows/ci.yml
@shijinyu
shijinyu ci: build fix
Latest commit a91949b on 22 May
 History
 2 contributors
@shijinyu@mingyang91
54 lines (48 sloc)  1.33 KB

name: Run Tests
on: [pull_request]

permissions:
  checks: write
  contents: write
env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN_GITHUB }}
    strategy:
      matrix:
        node_version: [16]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      # Cache the dependencies
      - name: Cache npm_modules
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.PNPM_CACHE_FOLDER }}
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-node_modules-
      # Install dependencies
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        id: setup-pnpm
        with:
          version: 7.1.2
          run_install: true

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
          eslint_extensions: tsx,ts,js,jsx
          # prettier: true
          # auto_fix: true
          # commit_message: 'fix(styles): fix code style issues with ${linter}'

      - name: Run tests
        run: pnpm typecheck && pnpm test
