name: Build and Publish to Github Package

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
jobs:
  # job to install, build
  cache-and-install:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [16]
        pnpm-version: [7.1.2]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # 1. Install Node.js
      - name: 1. Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # 2. Setup pnpm
      - name: 2. Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        id: setup-pnpm
        with:
          version: ${{ matrix.pnpm-version }}
          dest: ${{ env.PNPM_CACHE_FOLDER }}
          run_install: false

      # 3. Setup pnpm cache
      - name: 3. Setup pnpm cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.PNPM_CACHE_FOLDER }}
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-node_modules-

      # 4. Install dependencies
      - name: 4. Install dependencies
        id: install-dependencies
        run: pnpm install --frozen-lockfile

      # 5. build from source
      - name: 5. build from source
        run: pnpm run build

      # 6. Configure AWS credentials
      - name: 6. Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-east-1
          path: |
            ${{ env.PNPM_CACHE_FOLDER }}
            node_modules
            dist

      # 7. Login to Amazon ECR
      - name: 7. Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # 8. Login to Amazon ECR
      - name: push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: scene-web
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build  --build-arg NPM_AUTH_TOKEN=${{ secrets.NPM_AUTH_TOKEN_GITHUB }} -f APP-META/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        with:
          path: |
            ${{ env.PNPM_CACHE_FOLDER }}
            node_modules
            dist
